avast/wanna-ml

- src/wanna/core/deployment/monitoring.py
- src/wanna/core/deployment/vertex_pipelines.py
- src/wanna/core/services/base.py
- src/wanna/core/services/pipeline.py
- tests/pipeline/test_pipeline_service.py
4.1.6 - As a ML Engineer I can set a notification channel such as email for when a pipeline fails
> MLOPS-91 - Create a Vertex AI PipelineJob failed alerts

- .gitignore
- samples/pipelines/sklearn/wanna.yaml
- src/wanna/cli/plugins/pipeline_plugin.py
- src/wanna/core/deployment/monitoring.py
- src/wanna/core/services/pipeline.py
- src/wanna/core/utils/gcp.py
- src/wanna/core/utils/validators.py
This PR allows for wanna pipelines to accept any network
> MLOPS-94- wanna pipelines allow for shared networks

- .github/ISSUE_TEMPLATE/bug_report.yaml
> fix: typo in issue template

- src/wanna/core/models/docker.py
- src/wanna/core/services/docker.py
Workerpool can be set when using GCP Cloud Build
MLOPS-54
> feat(docker): allow setting of workerpool in cloud build

- src/wanna/core/services/jobs.py
Fixing casting bug in job manifest serialisation
> fix: jobs encryption spec key name fix

- src/wanna/core/models/notebook.py
- src/wanna/core/services/notebook.py
User-managed notebooks can now be started in collaborative mode.
> feat(notebooks): adding collaborative option

- src/wanna/core/services/managed_notebook.py
- src/wanna/core/services/notebook.py
- src/wanna/core/utils/config_enricher.py
> fix: wanna owner email

- src/wanna/cli/plugins/common_options.py
- src/wanna/cli/plugins/job_plugin.py
- src/wanna/cli/plugins/managed_notebook_plugin.py
- src/wanna/cli/plugins/notebook_plugin.py
- src/wanna/cli/plugins/pipeline_plugin.py
> feat: allow notebook and managed notebook version

- src/wanna/core/models/notebook.py
- src/wanna/core/services/notebook.py
> feat: user-notebook gcs backup 

- src/wanna/core/deployment/monitoring.py
> fix: Waits for log metric until ready

- poetry.lock
- pyproject.toml
- src/wanna/core/utils/config_enricher.py
- src/wanna/core/utils/credentials.py
- tests/conftest.py
- tests/mocks/mocks.py
- tests/pipeline/test_pipeline_service.py
> feat: add author label

- .pre-commit-config.yaml
- src/wanna/cli/__main__.py
- tests/init_templates/test_init_templates.py
> test: templates tests

- .github/workflows/SlackRelease.yml
Made a new GitHub actions to release notes about new releases to the Slack Channel
MLOPS-170
> feat: GitHub Releases to Slack

- .github/workflows/SlackRelease.yml
> fix: Forgot to format release.body to JSON. Should work now

- .github/workflows/SlackRelease.yml
> refactor: added wanna-ml to the title

- src/wanna/core/models/docker.py
- src/wanna/core/services/docker.py
Adds configuration for cloud build timeout
N/A
> feat: allow for custom cloud-build timeout

- samples/pipelines/sklearn/wanna.yaml
- src/wanna/cli/plugins/pipeline_plugin.py
- src/wanna/core/deployment/vertex_pipelines.py
- src/wanna/core/models/pipeline.py
- src/wanna/core/services/docker.py
- src/wanna/core/services/pipeline.py
- tests/pipeline/test_pipeline_service.py
Adds the option to set Kubeflow V2 pipeline catching option from wanna.yaml and to override it from local run
MLOPS-225
> feat: allow for setting kubeflow caching setting

- src/wanna/core/services/notebook.py
Enabled Vertex AI notebook extended ui
> feat: add extended ui metadata to user managed notebooks

- src/wanna/core/models/notebook.py
- src/wanna/core/services/managed_notebook.py
This PR tidies the network config for managed notebooks so that users can use Google Managed network
MLOPS-321
> feat: Allow the use of native VPC in managed notebooks

- samples/pipelines/sklearn/wanna.yaml
- src/wanna/core/deployment/models.py
- src/wanna/core/deployment/monitoring.py
- src/wanna/core/deployment/vertex_pipelines.py
- src/wanna/core/models/notification_channel.py
- tests/deployment/test_gcp_connector.py
- tests/pipeline/test_pipeline_service.py
This PR adds support for GCP PubSub notification channels.
MLOPS-328
> feat: MLOPS-328 - add support for pubsub notification channels

- src/wanna/core/utils/env.py
- tests/utils/test_env.py
fixes #97 but we can talk about the fix and maybe we should invert the logic of the disabling while keeping the name of the environment variable?
> fix: WANNA_GCP_ENABLE_REMOTE_VALIDATION  logic

- src/wanna/core/services/docker.py
- src/wanna/core/utils/gcp.py
- tests/conftest.py
* Fix missing import bug 
* Clean up wanna.core.utils.gcp 
* remove duplicated call to get gcp project_nbumeric id
> chore: adjust imports & cleanup unused gcp util functions

- src/wanna/core/services/docker.py
Fix bug and  simplify skip build feature
> fix: simplify skip build feature logic

- docs/tutorial/job.md
- src/wanna/core/services/docker.py
Fix link in docs
https://github.com/avast/wanna-ml/issues/120
> fix: Vertex jobs deprecated links

- src/wanna/core/models/notebook.py
> fix: notebook doc field

- src/wanna/core/utils/gcp.py
we are using the us-central1 too
Fixes #127
> chore: adding us-central1 region and zones to offline validation

- docs/tutorial/index.md
- src/wanna/cli/plugins/common_options.py
- src/wanna/core/utils/config_loader.py
- tests/cli/test_job_plugin.py
- tests/gcp_settings/test_gcp_profile.py
Fixes #128 . It was surprisingly easy to implement, and it offers great flexibility.
> feat: accepting wanna.yaml from stdin

- src/wanna/core/services/docker.py
> fix: I did 2 mistakes in such small feature

- src/wanna/core/deployment/models.py
- src/wanna/core/services/base.py
- src/wanna/core/services/jobs.py
- src/wanna/core/services/pipeline.py
This PR fixes issue with running `wanna pipeline build` without access to GCP, it tried to connect to GCP.
> fix: not attempting to gcp access
